// <auto-generated />
using System;
using AnimeBackend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AnimeBackend.Domain.Media.MediaItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiredFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiredTo")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChaptersRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChaptersTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalLinks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Related")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondarySource")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SourceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRussian")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("UserScore")
                        .HasColumnType("REAL");

                    b.Property<int>("VolumesRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedEpisodes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("AnimeBackend.Domain.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("AnimeBackend.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f701"),
                            Color = "#22c55e",
                            Icon = "pi-play",
                            IsHidden = false,
                            Name = "Смотрю",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f702"),
                            Color = "#3b82f6",
                            Icon = "pi-bookmark",
                            IsHidden = false,
                            Name = "Запланировано",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f703"),
                            Color = "#8b5cf6",
                            Icon = "pi-check-circle",
                            IsHidden = false,
                            Name = "Просмотрено",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f704"),
                            Color = "#f59e0b",
                            Icon = "pi-pause",
                            IsHidden = false,
                            Name = "Отложено",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f705"),
                            Color = "#ef4444",
                            Icon = "pi-times-circle",
                            IsHidden = false,
                            Name = "Брошено",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0f1a2b3c-4d5e-4f60-8a91-b2c3d4e5f706"),
                            Color = "#06b6d4",
                            Icon = "pi-replay",
                            IsHidden = false,
                            Name = "Пересматриваю",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("media_item_tags", b =>
                {
                    b.Property<string>("MediaItemsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("media_item_tags");
                });

            modelBuilder.Entity("media_item_tags", b =>
                {
                    b.HasOne("AnimeBackend.Domain.Media.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeBackend.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
