// <auto-generated />
using System;
using Anime.Database.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anime.Database.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20260312083657_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anime.Database.Entities.AnimeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModifierId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Animes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4cef5a7-bcb8-6f10-2a0f-eda636a68620"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            ProfileId = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064"),
                            Title = "anime1"
                        },
                        new
                        {
                            Id = new Guid("732ce9d6-4b0c-91a3-ecf8-3345ee27634c"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            ProfileId = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064"),
                            Title = "anime2"
                        });
                });

            modelBuilder.Entity("Anime.Database.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModifierId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("Anime.Database.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModifierId");

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            NickName = "system"
                        },
                        new
                        {
                            Id = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            NickName = "kotonai"
                        });
                });

            modelBuilder.Entity("Anime.Database.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModifierId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cee3bae9-7a1d-0bc0-0b1a-a2fbddc50cfb"),
                            AnimeId = new Guid("c4cef5a7-bcb8-6f10-2a0f-eda636a68620"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            Name = "tag1",
                            ProfileId = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064")
                        },
                        new
                        {
                            Id = new Guid("d8f72af3-b1e6-679f-a63a-f85e5e7b8a82"),
                            AnimeId = new Guid("c4cef5a7-bcb8-6f10-2a0f-eda636a68620"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            Name = "tag2",
                            ProfileId = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064")
                        },
                        new
                        {
                            Id = new Guid("c2df00ac-c1c5-8711-0601-a37c60d31626"),
                            AnimeId = new Guid("732ce9d6-4b0c-91a3-ecf8-3345ee27634c"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("7230b554-0e54-b8ee-f8e9-343e71f28176"),
                            Name = "tag3",
                            ProfileId = new Guid("c839e423-bbaa-7b5b-ab26-430ceda8f064")
                        });
                });

            modelBuilder.Entity("Anime.Database.Entities.AnimeEntity", b =>
                {
                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Profile")
                        .WithMany("Animes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Anime.Database.Entities.FileEntity", b =>
                {
                    b.HasOne("Anime.Database.Entities.AnimeEntity", "Anime")
                        .WithMany("Files")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Anime.Database.Entities.ProfileEntity", b =>
                {
                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("Anime.Database.Entities.TagEntity", b =>
                {
                    b.HasOne("Anime.Database.Entities.AnimeEntity", "Anime")
                        .WithMany("Tags")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anime.Database.Entities.ProfileEntity", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Anime.Database.Entities.AnimeEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Anime.Database.Entities.ProfileEntity", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
